### ISSUE TITLE
Issue#1

### ISSUE THREAD

**Issue by kanitmann** [kanitmann/tweeter#2]
Gem "guard livereload" currently not stable in the web app.

```bash
bundle exec guard init livereload
```
returns 

Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
`C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in require': cannot load such file -- 2.4/rubyeventmachine (LoadError) from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in require'`
from `C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in <top (required)>' from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in require'`
from `C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in rescue in require' from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in require'`
from `C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in <top (required)>' `from `C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in require'`
from` C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in rescue in require' from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in require'`
from `C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:10:in <top (required)>' `from `C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in require'`
from `C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in rescue in require'` from `C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in require'`
from `C:/Ruby24-x64/flutterbot/play.rb:3:in `

**Comment by ayushtamra** [comment]
Hey Kanit, this happened with me also, probably you are facing the same, for this you can refer to this:
[Unable to load the EventMachine C extension; To use the pure-ruby reactor](https://stackoverflow.com/questions/30682575/unable-to-load-the-eventmachine-c-extension-to-use-the-pure-ruby-reactor)
Also if you are facing difficulty with livereload you can try installing for your local system the latest version from [here](https://rubygems.org/gems/guard-livereload)

**Comment by kanitmann** [comment]
> 
> 
> Hey Kanit, this happened with me also, probably you are facing the same, for this you can refer to this:
> [Unable to load the EventMachine C extension; To use the pure-ruby reactor](https://stackoverflow.com/questions/30682575/unable-to-load-the-eventmachine-c-extension-to-use-the-pure-ruby-reactor)
> Also if you are facing difficulty with livereload you can try installing for your local system the latest version from [here](https://rubygems.org/gems/guard-livereload)

Ya, the EventMachine is still very unstable, but the GitHub build looks stable.

The livereload is yet not responding as expected and is giving errors. It might be due to my setup process. Nonetheless, I am closing this review for now, if problem persists, open a new issue.
